name: breadfast

on:
  push:
    branches:
    - master
  workflow_dispatch:
  schedule:
  - cron:  "59 23 * * *"

jobs:
  is-enabled:
    runs-on: ubuntu-latest
    outputs:
      enabled: ${{ steps.enabled.outputs.enabled }}
    steps:
    - id: enabled
      env:
        ENABLED: ${{ vars.ENABLED }}
      if: "${{ env.ENABLED == '1' }}"
      run: echo "enabled=1" >> $GITHUB_OUTPUT

  run-enabled:
    name: enabled
    runs-on: ubuntu-latest
    needs: [is-enabled]
    if: needs.is-enabled.outputs.enabled == '1'
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Run
      env:
        PASSCREATOR_API_KEY: ${{ secrets.PASSCREATOR_API_KEY }}
        PASSCREATOR_PASS_ID: ${{ secrets.BREADFAST_PASSCREATOR_PASS_ID }}
        BREADFAST_TOKEN: ${{ secrets.BREADFAST_TOKEN }}
        BREADFAST_GAMEBALL_API_KEY: ${{ secrets.BREADFAST_GAMEBALL_API_KEY }}
      run: make run -e APP=breadfast
