name: main

on:
  push:
    branches:
    - master
  schedule:
  - cron:  '59 23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Run
      env:
        MEMBERSHIP_NUM: ${{ secrets.MEMBERSHIP_NUM }}
        MEMBERSHIP_PIN: ${{ secrets.MEMBERSHIP_PIN }}
        PASSCREATOR_API_KEY: ${{ secrets.PASSCREATOR_API_KEY }}
        PASSCREATOR_PASS_ID: ${{ secrets.PASSCREATOR_PASS_ID }}
      run: make ci
    - name: Run (Loay)
      env:
        MEMBERSHIP_NUM: ${{ secrets.LOAY_MEMBERSHIP_NUM }}
        MEMBERSHIP_PIN: ${{ secrets.LOAY_MEMBERSHIP_PIN }}
        PASSCREATOR_API_KEY: ${{ secrets.PASSCREATOR_API_KEY }}
        PASSCREATOR_PASS_ID: ${{ secrets.LOAY_PASSCREATOR_PASS_ID }}
      run: make ci
