name: Main

on:
  push:
    branches:
    - master
  schedule:
  - cron:  '59 23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Run
      run: make
